// <auto-generated />
using Agencia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agencia.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110213858_primeira")]
    partial class primeira
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Agencia.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cpf_cliente");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_cliente");

                    b.Property<string>("EnderecoCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("endereco_cliente");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone_cliente");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CpfCliente = "111.895.787-11",
                            EmailCliente = "01@hotmail",
                            EnderecoCliente = "bla bla bla",
                            NomeCliente = "Ana",
                            TelefoneCliente = "1111"
                        },
                        new
                        {
                            Id = 2,
                            CpfCliente = "222.895.787-11",
                            EmailCliente = "02@hotmail",
                            EnderecoCliente = "logo ali",
                            NomeCliente = "Joana",
                            TelefoneCliente = "2222"
                        },
                        new
                        {
                            Id = 3,
                            CpfCliente = "333.895.787-11",
                            EmailCliente = "03@hotmail",
                            EnderecoCliente = "bla bla bla",
                            NomeCliente = "Mara",
                            TelefoneCliente = "3333"
                        },
                        new
                        {
                            Id = 4,
                            CpfCliente = "444.895.787-11",
                            EmailCliente = "04@hotmail",
                            EnderecoCliente = "logo ali",
                            NomeCliente = "Anderson",
                            TelefoneCliente = "4444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
